# Word cues on the final narration: aligned word times ([{w, a, b}] in narration seconds, e.g. from
# align.py mapped through any edits), each onset refined to the first voiced frame after the preceding
# pause so breaths don't trigger beats early. Writes an ES module with DURATION and WORDS [{i, w, t, e}].
# usage: uv run --with numpy --with soundfile word-cues.py <words.json> <narration.wav> <timeline.js>
import json, sys, numpy as np, soundfile as sf
words_path, audio_path, out_path = sys.argv[1:4]
words = json.load(open(words_path))
x, sr = sf.read(audio_path)
if x.ndim > 1: x = x.mean(1)
hop = 0.005; win = int(sr * 0.015)
db = np.array([20 * np.log10(np.sqrt(np.mean(x[i:i + win] ** 2) + 1e-12)) for i in range(0, len(x) - win, int(sr * hop))])
peak = np.percentile(db, 99.5)
fr = lambda t: max(0, min(len(db) - 1, int(round(t / hop))))
out = []
for i, w in enumerate(words):
    a = w["a"]; pe = words[i - 1]["b"] if i else 0.0
    lo, hi = max(pe - 0.05, a - 0.4), a + 0.12
    quiet = [k for k in range(fr(lo), fr(hi)) if all(db[k2] < peak - 40 for k2 in range(k, min(k + 8, len(db))))]
    onset = a - 0.02
    if quiet:
        q = quiet[-1] + 8
        v = next((k for k in range(q, fr(a + 0.35)) if db[k] > peak - 24), None)
        if v is not None: onset = v * hop
    out.append({"i": i, "w": w["w"], "t": round(onset, 3), "e": round(w["b"] + 0.04, 3)})
dur = len(x) / sr
open(out_path, "w").write("// Generated by word-cues.py: narration word cues in video seconds.\n"
    f"export const DURATION = {dur:.2f};\nexport const WORDS = {json.dumps(out, ensure_ascii=False)};\n")
print("  ".join(f"{o['i']}:{o['w']}@{o['t']}({o['t'] - w['a']:+.2f})" for o, w in zip(out, words)))
